//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LiftBuddyEntities : DbContext
    {
        public LiftBuddyEntities()
            : base("name=LiftBuddyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblFollower> tblFollowers { get; set; }
        public virtual DbSet<tblLevelLedger> tblLevelLedgers { get; set; }
        public virtual DbSet<tblNotification> tblNotifications { get; set; }
        public virtual DbSet<tblNotificationMaster> tblNotificationMasters { get; set; }
        public virtual DbSet<tblOtpTransaction> tblOtpTransactions { get; set; }
        public virtual DbSet<tblPointLedger> tblPointLedgers { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    
        [DbFunction("LiftBuddyEntities", "Split")]
        public virtual IQueryable<Split_Result> Split(string line, string splitOn)
        {
            var lineParameter = line != null ?
                new ObjectParameter("Line", line) :
                new ObjectParameter("Line", typeof(string));
    
            var splitOnParameter = splitOn != null ?
                new ObjectParameter("SplitOn", splitOn) :
                new ObjectParameter("SplitOn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[LiftBuddyEntities].[Split](@Line, @SplitOn)", lineParameter, splitOnParameter);
        }
    
        public virtual int AllDateWiseUserStatus(Nullable<int> userID, Nullable<System.DateTime> strt_date, Nullable<System.DateTime> end_date)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var strt_dateParameter = strt_date.HasValue ?
                new ObjectParameter("strt_date", strt_date) :
                new ObjectParameter("strt_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AllDateWiseUserStatus", userIDParameter, strt_dateParameter, end_dateParameter);
        }
    
        public virtual int DateWiseUserStatus(Nullable<int> userID, Nullable<System.DateTime> strt_date, Nullable<System.DateTime> end_date)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var strt_dateParameter = strt_date.HasValue ?
                new ObjectParameter("strt_date", strt_date) :
                new ObjectParameter("strt_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DateWiseUserStatus", userIDParameter, strt_dateParameter, end_dateParameter);
        }
    }
}
