//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    
    public partial class RequestListContainer
    {
        public decimal Id { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public Nullable<System.DateTime> JourneyDate { get; set; }
        public Nullable<int> NoOfPerson { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> UserId { get; set; }
    }
}
