//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbleOfferRide
    {
        public decimal Id { get; set; }
        public string StartAddress { get; set; }
        public string ViaDetail { get; set; }
        public string DestinationAddress { get; set; }
        public Nullable<System.DateTime> JourneyDate { get; set; }
        public Nullable<decimal> DriveVehicleTypeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> UserId { get; set; }
    }
}
